error: provide access to inner error within TracedError
This change makes TracedError a two-way door, making it
easier to adopt in a larger codebase.

This change provides an "escape hatch" to be able to read and
extract error stored within a TracedError. Among other things,
this will help adoption of TracedError by:

* allowing onboarding users to still match against error variants,
  as might be common in test cases

* allowing crate users to bypass missing or unreleased features

* allowing for partial migration of a codebase, so that TracedError
  can be used in one portion, and then the original error extracted
  at some interface above which TracedError is not yet used or wanted.